# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['app:3000'] # If using an exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
