apiVersion: apps/v1
kind: Deployment
metadata:
  name: whistle-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whistle
  template:
    metadata:
      labels:
        app: whistle
    spec:
      containers:
        - name: whistle
          image: your-docker-registry/whistle:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
